#pragma once

#include <ntifs.h>
#include <ntstrsafe.h>
#include <ntimage.h>

NTKERNELAPI
NTSTATUS
NTAPI
MmCopyVirtualMemory(
	IN PEPROCESS FromProcess,
	IN PVOID FromAddress,
	IN PEPROCESS ToProcess,
	OUT PVOID ToAddress,
	IN SIZE_T BufferSize,
	IN KPROCESSOR_MODE PreviousMode,
	OUT PSIZE_T NumberOfBytesCopied
);

NTKERNELAPI
NTSTATUS
NTAPI
PsLookupProcessThreadByCid(
	IN PCLIENT_ID ClientId,
	OUT PEPROCESS * Process,
	OUT PETHREAD * Thread
);

NTKERNELAPI
BOOLEAN
NTAPI
PsIsProtectedProcess(IN PEPROCESS Process);


NTKERNELAPI
PPEB
NTAPI
PsGetProcessPeb(IN PEPROCESS Process);

NTKERNELAPI
PVOID
NTAPI
PsGetThreadTeb(IN PETHREAD Thread);

NTKERNELAPI
PVOID
NTAPI
PsGetProcessWow64Process(IN PEPROCESS Process);

NTKERNELAPI
PVOID
NTAPI
PsGetCurrentProcessWow64Process();

#define DPRINT(format, ...) DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, format, __VA_ARGS__)

#define FFGAME_DEVICE_NAME L"ffgame"
#define FFGAME_DEVICE_FILE L"\\\\.\\" FFGAME_DEVICE_NAME

#define DEVICE_NAME     L"\\Device\\"     ## FFGAME_DEVICE_NAME
#define DOS_DEVICE_NAME L"\\DosDevices\\" ## FFGAME_DEVICE_NAME

#define FILE_DEVICE_FFGAME 0x8888

#define IOCTL_FFGAME_COPY_MEMORY  (ULONG)CTL_CODE(FILE_DEVICE_FFGAME, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_FFGAME_INJECT_DLL (ULONG)CTL_CODE(FILE_DEVICE_FFGAME, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
